name: CI / Tests

on:
  schedule:
    - cron: "00 00 * * 4" # every friday at 00:00
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install tree-sitter-cli
        uses: tree-sitter/setup-action@v2
        with:
          install-cli: true
          install-lib: false

      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.9.0

      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true

      - name: Install dependencies
        run: make install

      - name: Run tests
        run: make test
